version: '3.2'

services:
  postgres:
    image: postgres:11
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
    - 5432:5432
